# Generated by Django 3.1.7 on 2021-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='avatars/%y/%m/%d'),
        ),
    ]
