# Generated by Django 3.1.7 on 2021-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210308_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars/%y/%m/%d'),
        ),
    ]
