# Generated by Django 3.1.7 on 2021-03-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='photo/%y/%m/%d'),
        ),
    ]
