# Generated by Django 3.1.7 on 2021-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210308_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_followers'),
        ),
    ]
